### PR TITLE
Revert "Added a minimal logo as required!"

### PR DESCRIPTION
**Pull request by prabhupant**
Reverts prabhupant/python-ds#46

### CODE REVIEW

**Comment by srbhr** [comment]
Logo isn't displaying, and photo inside the logo folder is not showing up.

**Comment by prabhupant** [comment]
@srbhr That's because you need to mention the relative link, not the complete URL.
In this case it should have been `logo/logo.png`

**Comment by srbhr** [comment]
@prabhupant 
Should I make the changes then ??
change the link, then ?

**Comment by prabhupant** [comment]
Sure, go ahead and please make use lowercase letters only in the logo and make the logo say `python-ds` with everything in lowercase and with a hyphen in between python and ds. Otherwise, everything LGTM :smiley:

**Pull request merged**
