### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by shardul08**
Updated README to link data_structure and algorithms

### CODE REVIEW

**Comment by shardul08** [comment]
Should I open useful_links.md and link it to bookmarks directory?

**Comment by prabhupant** [comment]
There is no useful_links.md file now. It has been expanded into bookmarks directory with new markdown files inside it

**Comment by shardul08** [comment]
I am sorry, I meant Should I rename useful_links.md to bookmarks and link it to bookmarks directory?

**Comment by prabhupant** [comment]
Yeah. Then file the PR :smile:

**Pull request closed without merging**
