### PR TITLE
Deque Implementation

### PR DESCRIPTION
**Pull request by shotanozadze**
# Description
Added Deque implementation that uses python list. Deque is data structure. Personally me, I like it very much and use it often.
It is like stack but has some advantages, you can add elements in both sides, as in back, also in front. I think it's very useful data structure.

Please include a summary of the change and which issue is fixed or what question/feature you have added.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature/question

# Checklist:

- [ ] My code follows the style guidelines of this project i.e. [Pep8](https://www.python.org/dev/peps/pep-0008/)
- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Comment by shotanozadze** [comment]
Lint failure not because of my changes

**Comment by shotanozadze** [comment]
Thanks

**Comment by shotanozadze** [comment]
Removed but lint failure again...

**Comment by prabhupant** [comment]
Please remove `data_structures/deque/.DS_Store` and `data_structures/.DS_Store` also.
The lint will fail. It's something I have to fix but I just keep procrastinating :sweat_smile:. This weekend maybe

**Pull request merged**
