### PR TITLE
Programs added to algorithms/Dynamic_programming and data_structure/b…

### PR DESCRIPTION
**Pull request by amalbros**
…inary_trees

### CODE REVIEW

**Comment by amalbros** [comment]
Hey I dont have much experience with open source contributions.Should i do the corresponding changes in the branch and give a new pull request?

**Comment by prabhupant** [comment]
@amalbros I will write a comprehensive contribution guide and will let you know once I am done :smile:

**Comment by amalbros** [comment]
Have a look at the changes made

**Comment by prabhupant** [comment]
I have written a contribution guide here https://github.com/prabhupant/python-ds/blob/master/CONTRIBUTING.md

Please refer to it as you need to make some changes like adhering to the Pep8 styling, etc

**Comment by amalbros** [comment]
Please suggest the changes needed.since the guide is too long,i find difficulty in understanding what you expect me to do.I had change to snake cases as you suggested.I tried my best

**Comment by prabhupant** [comment]
For starters, add/update per question per PR as it becomes easier to review. Secondly, follow Pep8 styling guide. I think this article will suffice https://realpython.com/python-pep8/

**Comment by prabhupant** [comment]
Closing the PR due to inactivity

**Pull request closed without merging**
