### PR TITLE
Create Greedy_Algorithms

### PR DESCRIPTION
**Pull request by BiaHawk**
a file for the greedy algorithms, I already have one to put in this file

### CODE REVIEW

**Comment by prabhupant** [comment]
@BiaHawk is this going to be the index file? If yes, then please make it a markdown file by adding it extension as `.md` and use lowercase letters while naming files and directories

So in this case it should be `greedy_algorithms.md`.

**Comment by BiaHawk** [comment]
No, my idea is to put the greedy algorithms there, I already have one to put in the file, but I can put the algorithm directly on the graph file, bc dijkstra uses graph. Tell me what you think that it is better to do!

**Comment by prabhupant** [comment]
I think the better idea would be to create a separate file for each algorithm. That way navigating around the repo will be easier and I am considering creating a comprehensive doc and index for the whole repo. So a structure like `algorithms/dynamic_programming/`, `algorithms/greedy/`, etc will be the best for this repo.

**Comment by BiaHawk** [comment]
I don't think so, bc the person will have to search what algorithm file is the wanted algorithm. But okay, I will make your way

**Comment by prabhupant** [comment]
I have created the `greedy` directory under `algorithms`. Feel free to create a new file for each greedy algorithm you would like to implement. Looking forward to the PR! :smiley:

**Pull request closed without merging**
